// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctbnoayjouosyxroinyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0Ym5vYXlqb3Vvc3l4cm9pbnlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0OTY4NTUsImV4cCI6MjA3MDA3Mjg1NX0.cd8n8zxA_nBX93Vt77YmmjNDvpwqV5Z444cjysJVGUY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});